spring.application.name=portfolio
spring.datasource.url=jdbc:postgresql://db:5432/portfolio
spring.datasource.username=folioAdmin
spring.datasource.password=${PASSWORD_JAVA_DB}
spring.jpa.hibernate.ddl_auto=none
